---
  - name: 'Instalação do MYSQL'
    apt:
      name: "{{ item }}"
      state: present
    become: yes
    with_items:
      - python-mysqldb
      - mysql-server-5.7

  - name: 'Configurar usuário root'
    mysql_user:
      login_user: "{{ db_user_root }}"
      name: "{{ db_user_root }}"
      password:
    become: yes


  - name: 'Criar o banco de dados MYSQL'
    mysql_db:
      name: "{{ wp_db_name }}"
      login_user: "{{ db_user_root }}"
      state: present
    become: yes

  - name: 'Criar Usuario'
    mysql_user:
      name: "{{ wp_username }}"
      password: "{{ wp_user_password }}"
      priv: "{{ wp_db_name }}.*:ALL"
      login_user: "{{ db_user_root }}"
      state: present
      host: "{{ wp_ip }}"
    become: yes
  - name: 'Configuração de acesso ao banco'
    template:
      src: '/ansible/roles/mysql/templates/mysqld.cnf'
      dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    become: yes 
  - name: 'Abrindo porta MYSQL 3306'
    ufw:
      rule: allow
      port: 3306
    become: yes
    notify:
      - restart mysql
